// frontend/components/chat/MetadataModal.tsx
"use client";

import { useState } from "react";
import { MetadataRequestField } from "@/app/lib/llm-ui-events";
import { API_BASE } from "@/app/lib/config";

/* ================= PROPS ================= */

interface MetadataModalProps {
  /** Fields requested by backend */
  fields: MetadataRequestField[];

  /** Job / session id */
  sessionId: string;

  /** Called when metadata is successfully submitted */
  onSuccess: () => void;

  /** Optional cancel */
  onCancel?: () => void;
}

/* ================= CONSTANTS ================= */

// 🔒 Backend-owned identity fields (never editable)
const READ_ONLY_KEYS = [
  "company_document_id",
  "revision_number",
];

/* ================= COMPONENT ================= */

export default function MetadataModal({
  fields,
  sessionId,
  onSuccess,
  onCancel,
}: MetadataModalProps) {
  /* ---------------- FORM STATE ---------------- */

  const [values, setValues] = useState<Record<string, string>>(
    () =>
      Object.fromEntries(
        fields.map((f) => [f.key, ""])
      )
  );

  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  /* ================= HANDLERS ================= */

  function updateValue(key: string, value: string) {
    setValues((prev) => ({ ...prev, [key]: value }));

    // Clear error as soon as user edits
    if (error) setError(null);
  }

  async function handleSubmit() {
    if (loading) return;

    setLoading(true);
    setError(null);

    try {
      const res = await fetch(
        `${API_BASE}/metadata/update`,
        {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            job_id: sessionId,
            metadata: values,
          }),
        }
      );

      if (!res.ok) {
        throw new Error("Metadata submission failed");
      }

      onSuccess();
    } catch (err) {
      console.error(err);
      setError(
        "Could not submit the information. Please check the fields and try again."
      );
    } finally {
      setLoading(false);
    }
  }

  /* ---------------- DERIVED STATE ---------------- */

  // ✅ Only user-editable fields are required
  const isDisabled =
    loading ||
    fields.some((f) => {
      if (READ_ONLY_KEYS.includes(f.key)) return false;
      return !values[f.key]?.trim();
    });

  /* ================= RENDER ================= */

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70">
      <div className="w-full max-w-lg rounded-xl border border-white/10 bg-zinc-900 p-6 shadow-xl">
        {/* HEADER */}
        <h2 className="mb-2 text-lg font-semibold text-white">
          Additional information required
        </h2>
        <p className="mb-6 text-sm text-gray-400">
          Please provide the following details to continue.
        </p>

        {/* FORM */}
        <div className="space-y-4">
          {fields.map((field) => {
            const isReadOnly = READ_ONLY_KEYS.includes(field.key);

            return (
              <div key={field.key}>
                <label className="mb-1 block text-sm font-medium text-gray-300">
                  {field.label}
                </label>

                {field.reason && (
                  <p className="mb-1 text-xs text-gray-500">
                    {field.reason}
                  </p>
                )}

                {isReadOnly && (
                  <p className="mb-1 text-xs text-blue-400">
                    Auto-generated by system
                  </p>
                )}

                <input
                  type="text"
                  value={values[field.key]}
                  placeholder={
                    isReadOnly
                      ? "Auto-generated"
                      : field.placeholder
                  }
                  onChange={(e) =>
                    updateValue(field.key, e.target.value)
                  }
                  disabled={loading || isReadOnly}
                  className="
                    w-full rounded-md
                    border border-white/10
                    bg-black px-3 py-2
                    text-sm text-white
                    placeholder-gray-500
                    outline-none
                    focus:border-blue-500
                    disabled:opacity-60
                  "
                />
              </div>
            );
          })}
        </div>

        {/* ERROR */}
        {error && (
          <div className="mt-4 rounded-md bg-red-500/10 px-3 py-2 text-sm text-red-400">
            {error}
          </div>
        )}

        {/* ACTIONS */}
        <div className="mt-6 flex justify-end gap-3">
          {onCancel && (
            <button
              onClick={onCancel}
              disabled={loading}
              className="rounded-md px-4 py-2 text-sm text-gray-400 hover:text-white disabled:opacity-50"
            >
              Cancel
            </button>
          )}

          <button
            onClick={handleSubmit}
            disabled={isDisabled}
            className="rounded-md bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-500 disabled:opacity-50"
          >
            {loading
              ? "Submitting…"
              : error
              ? "Retry"
              : "Submit"}
          </button>
        </div>
      </div>
    </div>
  );
}
