# backend/rag/ingest.py

import os
import json
from typing import List, Dict, Any

import psycopg2

from langchain_postgres import PGVector
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_core.documents import Document
from backend.llm.hf_cache_utils import require_local_snapshot
from backend.llm.model_config_store import HF_CACHE_DIR
from backend.rag.collections import (
    DEFAULT_RAG_COLLECTION_NAME,
    normalize_collection_name,
)

COLLECTION_NAME = DEFAULT_RAG_COLLECTION_NAME

# ============================================================
# INTERNAL HELPERS
# ============================================================

def _normalize_conn(conn: str) -> str:
    if not conn:
        raise RuntimeError("DB connection string is required")
    return conn.replace("postgresql+psycopg2://", "postgresql://")

def _get_embeddings() -> HuggingFaceEmbeddings:
    # Matches backend/api/chat.py and forces local cache usage.
    return HuggingFaceEmbeddings(
        model_name=require_local_snapshot(HF_CACHE_DIR, "BAAI/bge-m3"),
        cache_folder=str(HF_CACHE_DIR),
        model_kwargs={"device": "cpu", "local_files_only": True},
        encode_kwargs={"normalize_embeddings": True},
    )


def _get_vector_store(connection_string: str, *, collection_name: str = COLLECTION_NAME) -> PGVector:
    return PGVector.from_existing_index(
        embedding=_get_embeddings(),
        collection_name=normalize_collection_name(collection_name),
        connection=connection_string,
    )


def delete_document_revision(
    *,
    connection_string: str,
    company_document_id: str,
    revision_number: str,
    collection_name: str = COLLECTION_NAME,
) -> int:
    """
    Delete one document revision from a specific PGVector collection.

    This is mainly used by benchmark runs so repeated indexing does not create
    duplicate chunks inside the same isolated test collection.
    """
    conn = psycopg2.connect(_normalize_conn(connection_string))
    cur = conn.cursor()

    cur.execute(
        """
        DELETE FROM langchain_pg_embedding AS e
        USING langchain_pg_collection AS c
        WHERE e.collection_id = c.uuid
          AND c.name = %s
          AND e.cmetadata->>'company_document_id' = %s
          AND e.cmetadata->>'revision_number' = %s
        """,
        (
            normalize_collection_name(collection_name),
            company_document_id,
            str(revision_number),
        ),
    )
    deleted_rows = int(cur.rowcount or 0)
    conn.commit()
    cur.close()
    conn.close()
    return deleted_rows

# ============================================================
# LOAD DOCUMENTS (FIXED: CAPTURE CHUNK ID)
# ============================================================

def load_documents(json_path: str) -> List[Document]:
    """
    Load enriched chunks from JSON into LangChain Documents.
    
    🔥 FIX 1: Flattens cmetadata into main metadata.
    🔥 FIX 2: Explicitly captures 'chunk_id' from top-level JSON.
    """

    with open(json_path, "r", encoding="utf-8") as f:
        raw = json.load(f)

    documents: List[Document] = []

    for item in raw:
        content = item.get("page_content")
        metadata = item.get("metadata", {})
        cmetadata = item.get("cmetadata")
        
        #  NEW: Capture the ID generated by metadata.py
        chunk_id = item.get("chunk_id")

        if not content or not cmetadata:
            continue

        if "company_document_id" not in cmetadata:
            raise RuntimeError("Missing company_document_id in cmetadata")

        if "revision_number" not in cmetadata:
            raise RuntimeError("Missing revision_number in cmetadata")

        # 🔥 FLATTEN: Merge identity directly into top-level metadata
        combined_metadata = {
            **metadata,
            **cmetadata 
        }
        if not chunk_id:
            raise RuntimeError("chunk_id missing during ingest")

        #  NEW: Inject chunk_id into metadata so it gets saved to DB
        combined_metadata["chunk_id"] = chunk_id

        documents.append(
            Document(
                page_content=content,
                metadata=combined_metadata,
            )
        )

    if not documents:
        raise RuntimeError("No valid chunks loaded from JSON")

    return documents


# ============================================================
# CHUNK QUALITY SCORING (at ingest time)
# ============================================================

def score_chunk_quality(content: str) -> Dict[str, Any]:
    """
    Score a chunk's retrieval quality based on content characteristics.
    Called at ingest time — result stored in metadata.

    Scores 0.0–1.0 on 3 signals:
    - Length score:   too short/long chunks are harder to retrieve well
    - Density score:  ratio of alpha chars (avoids noise/gibberish chunks)
    - Richness score: number of distinct meaningful words (>3 chars)

    Returns: {"quality_score": float, "quality_tier": "high"|"medium"|"low"}
    """
    import re as _re

    default = {"quality_score": 0.5, "quality_tier": "medium"}
    if not content:
        return default

    try:
        # 1. Length score (optimal: 200–1500 chars)
        length = len(content)
        if length < 50:
            length_score = 0.1
        elif length < 200:
            length_score = 0.5
        elif length <= 1500:
            length_score = 1.0
        elif length <= 3000:
            length_score = 0.7
        else:
            length_score = 0.4

        # 2. Density score (fraction of alpha chars)
        alpha_chars = sum(1 for c in content if c.isalpha())
        density_score = min(alpha_chars / max(length, 1), 1.0)

        # 3. Richness score (distinct words > 3 chars, capped at 50)
        words = _re.findall(r"[a-zA-Z]{4,}", content.lower())
        distinct = len(set(words))
        richness_score = min(distinct / 50.0, 1.0)

        overall = round(
            0.3 * length_score + 0.3 * density_score + 0.4 * richness_score, 3
        )

        if overall >= 0.70:
            tier = "high"
        elif overall >= 0.40:
            tier = "medium"
        else:
            tier = "low"

        return {"quality_score": overall, "quality_tier": tier}

    except Exception as e:
        print(f"[INGEST] score_chunk_quality error (non-fatal): {e}")
        return default


# ============================================================
# INGEST DOCUMENT REVISION (NO DELETION, REVISION SAFE)
# ============================================================

def ingest_to_pgvector(
    *,
    documents: List[Document],
    connection_string: str,
    company_document_id: str,
    revision_number: str, #  FIX: Changed to str for enterprise support
    collection_name: str = COLLECTION_NAME,
    replace_existing: bool = False,
) -> None:
    """
    Ingest a document revision into PGVector.
    """

    if not documents:
        raise RuntimeError("No documents provided for ingestion")

    resolved_collection_name = normalize_collection_name(collection_name)
    vector_store = _get_vector_store(
        connection_string,
        collection_name=resolved_collection_name,
    )

    # --------------------------------------------------------
    # 🔒 DEFENSIVE IDENTITY CHECK (FIXED)
    # --------------------------------------------------------

    for doc in documents:
        # Check top-level metadata (since we flattened it)
        cm = doc.metadata 

        if cm.get("company_document_id") != company_document_id:
            raise RuntimeError(
                "company_document_id mismatch during ingest"
            )

        #  FIX: Strict string comparison for revisions
        if str(cm.get("revision_number")) != str(revision_number):
            raise RuntimeError(
                f"revision_number mismatch during ingest: "
                f"doc={cm.get('revision_number')} expected={revision_number}"
            )

    # --------------------------------------------------------
    # INGEST
    # --------------------------------------------------------

    if replace_existing:
        deleted_rows = delete_document_revision(
            connection_string=connection_string,
            company_document_id=company_document_id,
            revision_number=revision_number,
            collection_name=resolved_collection_name,
        )
        print(
            "[INGEST] Cleared existing chunks before re-index | "
            f"collection={resolved_collection_name} deleted_rows={deleted_rows}"
        )

    vector_store.add_documents(documents)

    setup_keyword_search(connection_string)


# ============================================================
# METADATA UPDATE (POST-CONFIRMATION)
# ============================================================

def update_vector_metadata(
    *,
    connection_string: str,
    company_document_id: str,
    revision_number: str, 
    updated_metadata: Dict[str, Any],
) -> None:
    """
    Update cmetadata for ALL chunks of a document revision.
    """

    if not updated_metadata:
        return

    conn = psycopg2.connect(_normalize_conn(connection_string))
    cur = conn.cursor()

    cur.execute(
        """
        UPDATE langchain_pg_embedding
        SET cmetadata = cmetadata || %s::jsonb
        WHERE cmetadata->>'company_document_id' = %s
          AND cmetadata->>'revision_number' = %s
        """,
        (
            json.dumps(updated_metadata),
            company_document_id,
            str(revision_number),
        ),
    )

    conn.commit()
    cur.close()
    conn.close()


# ============================================================
# DUPLICATE METADATA CHECK
# ============================================================

def metadata_exists(
    *,
    connection_string: str,
    metadata: Dict[str, Any],
) -> bool:
    """
    Check if similar cmetadata already exists.
    """

    if not metadata:
        return False

    conn = psycopg2.connect(_normalize_conn(connection_string))
    cur = conn.cursor()

    conditions = []
    values = []

    for k, v in metadata.items():
        conditions.append("cmetadata->>%s = %s")
        values.extend([k, str(v)])

    query = f"""
        SELECT 1
        FROM langchain_pg_embedding
        WHERE {' AND '.join(conditions)}
        LIMIT 1
    """

    cur.execute(query, values)
    exists = cur.fetchone() is not None

    cur.close()
    conn.close()

    return exists


# ============================================================
# KEYWORD SEARCH SUPPORT
# ============================================================

def setup_keyword_search(connection_string: str) -> None:
    """
    Create keyword search index (idempotent).
    """

    conn = psycopg2.connect(_normalize_conn(connection_string))
    cur = conn.cursor()

    cur.execute(
        """
        ALTER TABLE langchain_pg_embedding
        ADD COLUMN IF NOT EXISTS content_tsv tsvector
        GENERATED ALWAYS AS (
            to_tsvector('english', document)
        ) STORED;
        """
    )

    cur.execute(
        """
        CREATE INDEX IF NOT EXISTS
        langchain_pg_embedding_content_tsv_idx
        ON langchain_pg_embedding
        USING GIN (content_tsv);
        """
    )

    conn.commit()
    cur.close()
    conn.close()
